jobs:
- job: "YamlFileValidation12"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm run tsc && node script/newTestScript.js'
    displayName: 'Yaml File Validation1'
